# Generated by Django 5.2.1 on 2026-03-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
    ]
